version: "1"
rules:
  - base: master
    upstream: BGmi:master    # change `wei` to the owner of upstream repo
    mergeMethod: rebase
  - base: dev
    upstream: BGmi:dev    # change `wei` to the owner of upstream repo
    mergeMethod: force-push
